import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import barPic from "../../assets/rest-bar.jpg";
import { Box } from "@chakra-ui/react";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

export default function Mesa() {
  const router = useRouter();
  const id = router.query.id;
  const [mesa, setMesa] = useState(null);
  const [mesausuario, setMesausuario] = useState(null);


   useEffect(() => {
    if(router.isReady) {
       setMesausuario(id)
    }
   }, [router.isReady]);

  return (
    <Box className={styles.container}>
      <Head>
        <title>Rest-bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className={styles.cabecera}>
        <h1> Aplicación Test </h1>
      </Box>

      <Box className={styles.maqueta}>
        <Box
          className={styles.mesa1}
          onClick={() => {
            setMesa(1);
          }}
        >
          <p>1</p>
        </Box>
        <Box
          className={styles.mesa2}
          onClick={() => {
            setMesa(2);
          }}
        >
          <p>2</p>
        </Box>
        <Box
          className={styles.mesa3}
          onClick={() => {
            setMesa(3);
          }}
        >
          <p>3</p>
        </Box>

        <Box
          className={styles.mesa4}
          onClick={() => {
            setMesa(4);
          }}
        >
          <p>4</p>
        </Box>

        <Image src={barPic} width={"800px"} height={"500px"}></Image>
      </Box>

      {!mesa ? null : (
        <Box>
          <Box className={styles.opcionelegida}>
            <h3>Seleccionaste la mesa número: {mesa}</h3>
          </Box>

          <Box className={styles.opcionelegida}>
            <h3>Te encontrás en la mesa: {mesausuario}</h3>
          </Box>
        </Box>    
      )}
    </Box>
  );
}
